### ISSUE TITLE
Make as a package

### ISSUE THREAD

**Issue by vadimirtlach** [bloodwass/mixout#10]
When I want to import classes, e.g. MixLinear, to my code, I must write the whole path `from mixout.module import MixLinear`, sometimes it is not very comfortable so the solution is to do library as the package just add `__init__.py` and import all classes there. The results will be `from mixout import MixLinear`. Good luck! Thank you for great library!

**Comment by bloodwass** [comment]
Thank you for your suggestion. I've added it based on your pull request!
